### ISSUE TITLE
Why rand() for ids?

### ISSUE THREAD

**Issue by gkostov** [Aasim-A/AsyncTimer#10]
Hi,

I was wondering why the ids get generated by `rand()`? Reason being that it may not be actually needed - each call occupies a slot that has an unique index within `m_callsArray`. And also `rand()` has a chance of generating duplicates (even though it's a tiny chance) and if a duplicate occurs then the loops in `changeDelay()`, `delay()`, `reset()` and `cancel()` will update/cancel all slots that match. And it might be a good idea to put a `break;` in those loops if ids still have to be used (there will be no need for a loop if they get looked up by the index).

I can make the changes but wanted to know your opinion before that.

Cheers

**Comment by Aasim-A** [comment]
Hi gkostov, thanks for mentioning that, actually it's that way because in previous versions the lib used to use `vectors` which have variable length hence the need for random ids, but when I changed it to its current form, I forgot about that part.
Ids in this case would be unnecessary, and removing them could make things a lot simpler and more performant.
If you are willing to make a PR that would be great, otherwise I'll make these changes when I have time.

**Comment by gkostov** [comment]
Great, thanks!

Then one other thing - I'd love to have the "id" returned form the library to be "nullable" - that is, to have a way to clear the value of a variable holding that index so it won't be used again. So an `unsigned short` will not work because every possible value can be a valid index. Unless the value 0 is reserved (meaning `nothing here`) and indexes are returned as `availableIndex + 1`. So the library will be returning ids where each id is (the internal index + 1).

And will be even better if `cancel()` would accept ids by reference like `void cancel(unsigned short& id)` and clears the id itself.

What do you think?

**Comment by gkostov** [comment]
Working more with this I think that returning the index is not a good idea. I'm experimenting with a counter variable to provide the ids. And it seem that clearing the id variable of user code may be beyond the responsibilities of a library.
So the only thing I have yet is about changing the `= rand()` call to something like `= ++m_nextId`. I can get a PR for it if it looks right.

**Comment by Aasim-A** [comment]
What's the problem with returning the index? have you experimented with it?

**Comment by gkostov** [comment]
The problem I see is that if the returned id is related to the index there could be the case where you schedule a callback and it gets set on slot index 3 for example. The time comes and the callback is invoked and the slot is deactivated. Then you schedule another callback and accidentally it gets on slot 3 again (because it is available) and the slot becomes active again. But if some code keeps the old callback's id (which is 3) and has no idea if it has been triggered or not but wants to make sure it does not run anymore, then it will call `cancel(3)` and will effectively cancel the new callback.
I think the returned id must be related to the invocation (thus the `++m_nextId` suggestion) and not to the slot index.
In my code I have 

```javascript
void clearTimeout(unsigned short& id){
  asyncTimer.cancel(id);
  id = 0;
}
```
which helps with multiple calls to `cancel()` by clearing the `id` variable but does not help with callbacks that have been triggered and their `id` variables remaining set. Which is why earlier I suggested to have `void cancel(unsigned short& id)` to clear the `id` variable but I'm not convinced if this needs to be in the library or not :) ...

**Comment by Aasim-A** [comment]
Gotcha, lets go with the id counter then, but we'd have to use an `unsigned long` to not worry about the counter running out, as for the `cancel` to set the `id` to 0, I think that would make things harder to debug from the user's side, so I think it's better to keep the library contained to its self. If you could make a PR that would be great

**Comment by gkostov** [comment]
What is this one for https://github.com/Aasim-A/AsyncTimer/blob/master/src/AsyncTimer.h#L31 ? I don't see this being used anywhere in the code.
```javascript
class AsyncTimer {
private:
  struct m_TimerInfo {
    unsigned short id;  // < < < < < <  this one
    void (*callback)();
    unsigned long delayByMs;
```

**Comment by Aasim-A** [comment]
How? that's the id, the `m_callsArray` is an array of this struct, so `m_callsArray[0].id` is this id

**Comment by gkostov** [comment]
Aaaah, sorry! May be a bit too late in the evening right now and I saw it as being on the class definition.
Everything is good! Cheers!

**Comment by gkostov** [comment]
Hopefully this one is reasonable ...
Will this method be redundant without random ids https://github.com/Aasim-A/AsyncTimer/blob/master/src/AsyncTimer.cpp#L3 ?
```javascript
void AsyncTimer::setup() { srand(millis()); }
```

**Comment by Aasim-A** [comment]
Yes! this is just to increase the randomness of the `rand` function

**Comment by Aasim-A** [comment]
That function needs to remain and be deprecated though, to retain backwards compatibility

**Comment by gkostov** [comment]
Calling the function is more of a side effect than a feature of the library. Is the deprecation process to protect those relying on the side effect?

**Comment by Aasim-A** [comment]
no, but to make their application still compile and not throw an error, or we could do a major version release, what do you think?

**Comment by gkostov** [comment]
Yes, I think deprecating it is correct.

**Comment by Aasim-A** [comment]
> Ok, I get it - `::setup()` needs to remain and `srand()` can go, right?
> And, would it be right to use this above `setup()`
> ```c++
> [[deprecated("Not needed anymore and will be gone at some point")]]
> ```

Yep, that's right, but the `setup` function should be empty as the function is not needed anymore, the depreciation message should be something like this:
`Not needed anymore, will be removed in future versions`

**Comment by gkostov** [comment]
Apologies, I've got a cold these days and my mind is a bit slow.
Thanks for clearing it up for me :)
