### ISSUE TITLE
How to cancel all timeouts/intervals without having a reference to the id?

### ISSUE THREAD

**Issue by alexandermcpherson** [Aasim-A/AsyncTimer#14]
As the title suggests...

Lets say I have a function that has many timeouts and intervals within that function at that scope. How would I go about cancelling all of them where I don't keep a reference to them. Is this possible with the current version. I know I can cancel each one if I create a referecne to the ID, but if I have over 100 having to keep a reference to each one is a lot?

**Comment by Aasim-A** [comment]
Currently it's not possible without the `ids`, but that would be a good addition to the `api`, I'll try to get it done as soon as I can.

**Comment by alexandermcpherson** [comment]
@Aasim-A Nice one mate thank you. You'll see your work here with my custom robot! https://t800controller.com/demos.html so its getting some good use :-)

**Comment by Aasim-A** [comment]
Very impressive work with your robot, the feature you requested is now online 🚀

**Comment by alexandermcpherson** [comment]
@Aasim-A You're the man :-) all working here thanks a lot for doing that.
