### ISSUE TITLE
Error on ESP8266 Can't compile!

### ISSUE THREAD

**Issue by mano1979** [Aasim-A/AsyncTimer#16]
/Users/biletsky/Documents/Arduino/libraries/AsyncTimer/src/AsyncTimer.cpp:66:6: error: default argument given for parameter 1 of 'void AsyncTimer::cancelAll(bool)' [-fpermissive]
   66 | void AsyncTimer::cancelAll(bool includeIntervals = true) {
      |      ^~~~~~~~~~
In file included from /Users/biletsky/Documents/Arduino/libraries/AsyncTimer/src/AsyncTimer.cpp:1:
/Users/biletsky/Documents/Arduino/libraries/AsyncTimer/src/AsyncTimer.h:72:8: note: previous specification in 'void AsyncTimer::cancelAll(bool)' here
   72 |   void cancelAll(bool includeIntervals = true);
      |        ^~~~~~~~~
exit status 1
Error compiling for board Generic ESP8266 Module.

**Comment by d4nbanan** [comment]
I have the same error on ESP32(wemos lolin 32 lite)

**Comment by d4nbanan** [comment]
I solved this problem by removing method cancelAll from library code(.cpp)

**Comment by oxo42** [comment]
Another workaround is to rollback to version 2.2.0

**Comment by Aasim-A** [comment]
The issue should be fixed now guys 🚀, sorry for the late fix as I was busy
