### ISSUE TITLE
Call function with args

### ISSUE THREAD

**Issue by alexandermcpherson** [Aasim-A/AsyncTimer#6]
Can we not call functions and pass in arguments? i.e `t.setTimeout(lightEyes(true), 40000);`

**Comment by Aasim-A** [comment]
No, it doesn't work that way, `setTimeout` expects a function to be passed to its first argument, the example that you gave executes the function and passes the result of the executed function as the first argument of `setTimeout`, the function to be passed must not have any arguments and return `void`

**Comment by Aasim-A** [comment]
you can do this instead:
```c++
t.setTimeout([]() {
  lightEyes(true);
}, 40000);
```

**Comment by alexandermcpherson** [comment]
Ok thats brill thanks for clearing up
